[openai]
api_key = "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"

[ncbi]
base_url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/"

[assistant]
id = "asst_fEbBTAziC93bXGhVbIbbUQ5V"
thread_id = "thread_MyngT1Kbthb0wv49ov1U1o86"
